export const brands = [
  {
    id: 101,
    image: null,
    name: 'Schneider Electric',
    add_date: '',
    category_id: 1,
  },
  { id: 102, image: null, name: 'Hager', add_date: '', category_id: 1 },
  { id: 103, image: null, name: 'Legrand', add_date: '', category_id: 1 },
  { id: 104, image: null, name: 'ABB', add_date: '', category_id: 1 },
  { id: 105, image: null, name: 'Viko', add_date: '', category_id: 1 },
  { id: 106, image: null, name: 'Berker', add_date: '', category_id: 1 },
  { id: 107, image: null, name: 'Bemis', add_date: '', category_id: 1 },
  { id: 108, image: null, name: 'Giselt', add_date: '', category_id: 1 },
  {
    id: 201,
    image: null,
    name: 'Schneider Electric',
    add_date: '',
    category_id: 2,
  },
  { id: 202, image: null, name: 'Hager', add_date: '', category_id: 2 },
  { id: 203, image: null, name: 'АСКО', add_date: '', category_id: 2 },
  { id: 204, image: null, name: 'Takel', add_date: '', category_id: 2 },
  { id: 205, image: null, name: 'Chint', add_date: '', category_id: 2 },
  {
    id: 301,
    image: null,
    name: 'Schneider Electric',
    add_date: '',
    category_id: 3,
  },
  { id: 302, image: null, name: 'Hager', add_date: '', category_id: 3 },
  { id: 303, image: null, name: 'АСКО', add_date: '', category_id: 3 },
  { id: 701, image: null, name: 'ШВВП', add_date: '', category_id: 7 },
  { id: 702, image: null, name: 'ПВС', add_date: '', category_id: 7 },
  { id: 703, image: null, name: 'ПВ-1', add_date: '', category_id: 7 },
  { id: 704, image: null, name: 'ПВ-3', add_date: '', category_id: 7 },
  { id: 705, image: null, name: 'АВВГ', add_date: '', category_id: 7 },
  { id: 706, image: null, name: 'ВВГнг', add_date: '', category_id: 7 },
  { id: 707, image: null, name: 'ВВГнгд', add_date: '', category_id: 7 },
  { id: 708, image: null, name: 'ВВГП нг', add_date: '', category_id: 7 },
  {
    id: 709,
    image: null,
    name: 'Акустичний провід',
    add_date: '',
    category_id: 7,
  },
  {
    id: 710,
    image: null,
    name: 'Телевізійний та мережевий кабель',
    add_date: '',
    category_id: 7,
  },
  {
    id: 711,
    image: null,
    name: 'Гофра пластикова',
    add_date: '',
    category_id: 7,
  },
  { id: 712, image: null, name: 'Металорукав', add_date: '', category_id: 7 },
  { id: 713, image: null, name: 'Кабель-канали', add_date: '', category_id: 7 },
  {
    id: 714,
    image: null,
    name: 'Металеві лотки',
    add_date: '',
    category_id: 7,
  },
  {
    id: 1001,
    image: null,
    name: ' Ryxon (мат)',
    add_date: '',
    category_id: 10,
  },
  {
    id: 1002,
    image: null,
    name: 'Ryxon (кабель)',
    add_date: '',
    category_id: 10,
  },
  {
    id: 1003,
    image: null,
    name: 'Nexons (мат)',
    add_date: '',
    category_id: 10,
  },
  {
    id: 1004,
    image: null,
    name: 'Nexons (кабель)',
    add_date: '',
    category_id: 10,
  },
];
