export const categories = [
  {
    id: 1,
    image: null,
    name: 'Розетки та вимикачі',
    add_date: '',
  },
  {
    id: 2,
    image: null,
    name: 'Автоматичні вимикачі, УЗО',
    add_date: '',
  },
  {
    id: 3,
    image: null,
    name: 'Шини, клемники, клеми, гребінки',
    add_date: '',
  },
  {
    id: 4,
    image: null,
    name: 'Релейне обладнання',
    add_date: '',
  },
  {
    id: 5,
    image: null,
    name: 'Лючки та розеткові модулі',
    add_date: '',
  },
  {
    id: 6,
    image: null,
    name: 'Бокси під автомати (щити)',
    add_date: '',
  },
  {
    id: 7,
    image: null,
    name: 'Кабель, провід',
    add_date: '',
  },
  {
    id: 8,
    image: null,
    name: 'Ізолюючі матеріали та кріплення',
    add_date: '',
  },
  {
    id: 9,
    image: null,
    name: 'Терморегулятори',
    add_date: '',
  },
  {
    id: 10,
    image: null,
    name: 'Тепла підлога',
    add_date: '',
  },
  {
    id: 11,
    image: null,
    name: 'Коробки монтажні та розподільні',
    add_date: '',
  },
  {
    id: 12,
    image: null,
    name: 'Подовжувачі та колодки',
    add_date: '',
  },
  {
    id: 13,
    image: null,
    name: 'Освітлення',
    add_date: '',
  },
  {
    id: 14,
    image: null,
    name: 'Вентилятори',
    add_date: '',
  },
  {
    id: 15,
    image: null,
    name: 'Стабілізатори',
    add_date: '',
  },
  {
    id: 16,
    image: null,
    name: 'Вимірювальне обладнання та інструменти',
    add_date: '',
  },
];
