export const partners = [
  {
    id: '1',
    name: 'SE',
    logo: '/partners-logo/SE-logo.svg',
    url: 'https://www.se.com/ua/uk/',
  },
  {
    id: '2',
    name: 'Hager',
    logo: '/partners-logo/Hager-logo.svg',
    url: 'https://www.hager.ua/',
  },
  {
    id: '3',
    name: 'Viko',
    logo: '/partners-logo/viko-logo.svg',
    url: 'https://viko.net.ua/uk/',
  },
  {
    id: '4',
    name: 'Takel',
    logo: '/partners-logo/Takel-logo.svg',
    url: 'https://takel.ua/',
  },
  {
    id: '5',
    name: 'Acko',
    logo: '/partners-logo/asko-logo.svg',
    url: 'https://www.acko.ua/',
  },
  {
    id: '6',
    name: 'Chint',
    logo: '/partners-logo/Chint-logo.svg',
    url: 'https://chint.ua/',
  },
  {
    id: '7',
    name: 'Digitop',
    logo: '/partners-logo/DigiTop-logo.svg',
    url: 'https://digitop.ua/',
  },
  {
    id: '8',
    name: 'Biom',
    logo: '/partners-logo/biom-logo.svg',
    url: 'https://biom.ua/',
  },
  {
    id: '9',
    name: 'Plank',
    logo: '/partners-logo/Plank-logo.svg',
    url: 'https://plank.ua/',
  },
  {
    id: '10',
    name: 'ElectroHouse',
    logo: '/partners-logo/ElectroHouse-logo.svg',
    url: 'https://eh-electro-house.ua/',
  },
  {
    id: '11',
    name: 'novatek-electro',
    logo: '/partners-logo/novatekElectro-logo.svg',
    url: 'https://novatek-electro.com/',
  },
  {
    id: '12',
    name: 'tnsy',
    logo: '/partners-logo/tnsy-logo.svg',
    url: 'https://tnsy.com.ua/',
  },
  {
    id: '13',
    name: 'etron',
    logo: '/partners-logo/Etron-logo.svg',
    url: 'https://etron.com.ua/',
  },
  {
    id: '14',
    name: 'svittex',
    logo: '/partners-logo/Svittex-logo.svg',
    url: 'https://www.svittex.ua/ru/',
  },
  {
    id: '15',
    name: 'norte',
    logo: '/partners-logo/Norte-logo.svg',
    url: 'https://norte.com.ua/',
  },
  {
    id: '16',
    name: 'ds-electronics',
    logo: '/partners-logo/DS-Electronics-logo.svg',
    url: 'https://ds-electronics.com.ua/ru/rele/d25/',
  },
  {
    id: '17',
    name: 'vegasmartsolutions',
    logo: '/partners-logo/AllHub-logo.svg',
    url: 'https://vegasmartsolutions.net/',
  },
  {
    id: '18',
    name: 'ryxon',
    logo: '/partners-logo/Ryxon-logo.svg',
    url: 'https://ryxon.eu/about',
  },
  {
    id: '19',
    name: '/kablex',
    logo: '/partners-logo/KABLEX-logo.svg',
    url: 'https://kablex.ua/',
  },
  {
    id: '20',
    name: 'etigroup',
    logo: '/partners-logo/ETI-logo.svg',
    url: 'https://www.etigroup.eu/',
  },
  {
    id: '21',
    name: 'dkc',
    logo: '/partners-logo/DKC-logo.svg',
    url: 'https://dkc.ua/',
  },
  {
    id: '22',
    name: 'zzcm',
    logo: '/partners-logo/33KM-logo.svg',
    url: 'https://www.zzcm.com.ua/',
  },
  {
    id: '23',
    name: 'kron',
    logo: '/partners-logo/Kron-logo.svg',
    url: 'https://kron.ua/ua/',
  },
  {
    id: '24',
    name: 'wago',
    logo: '/partners-logo/Wago-logo.svg',
    url: 'https://www.wago.com/global/',
  },
  {
    id: '25',
    name: 'rubezh',
    logo: '/partners-logo/Rubezh-logo.svg',
    url: 'https://rubezh.systems/',
  },
];
