export const partners = [
  { id: '1', logo: '', url: 'https://www.se.com/ua/uk/' },
  { id: '2', logo: '', url: 'https://www.hager.ua/' },
  { id: '3', logo: '', url: 'https://viko.net.ua/uk/' },
  { id: '4', logo: '', url: 'https://takel.ua/' },
  { id: '5', logo: '', url: 'https://www.acko.ua/' },
  { id: '6', logo: '', url: 'https://chint.ua/' },
  { id: '7', logo: '', url: 'https://digitop.ua/' },
  { id: '8', logo: '', url: 'https://biom.ua/' },
  { id: '9', logo: '', url: 'https://plank.ua/' },
  { id: '10', logo: '', url: 'https://eh-electro-house.ua/' },
  { id: '11', logo: '', url: 'https://novatek-electro.com/' },
  { id: '12', logo: '', url: 'https://tnsy.com.ua/' },
  { id: '13', logo: '', url: 'https://etron.com.ua/' },
  { id: '14', logo: '', url: 'https://www.svittex.ua/ru/' },
  { id: '15', logo: '', url: 'https://norte.com.ua/' },
  { id: '16', logo: '', url: 'https://ds-electronics.com.ua/ru/rele/d25/' },
  { id: '17', logo: '', url: 'https://vegasmartsolutions.net/' },
  { id: '18', logo: '', url: 'https://ryxon.eu/about' },
  { id: '19', logo: '', url: 'https://kablex.ua/' },
  { id: '20', logo: '', url: 'https://www.etigroup.eu/' },
  { id: '21', logo: '', url: 'https://dkc.ua/' },
  { id: '22', logo: '', url: 'https://www.zzcm.com.ua/' },
  { id: '23', logo: '', url: 'https://kron.ua/ua/' },
  { id: '24', logo: '', url: 'https://digitop.ua/about' },
  { id: '25', logo: '', url: 'https://www.wago.com/global/' },
  { id: '26', logo: '', url: 'https://rubezh.systems/' },
];
