export const products = [
  {
    id: 1,
    vendorCode: '1',
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    measurementUnit: 'шт',
    brand: 'Schneider',
    price: 4443,
    description: '',
    image: '',
    series: 'Asfora',
    series_id: '1',
    brand_id: '1',
  },
  {
    id: 2,
    vendorCode: '2',
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    measurementUnit: 'шт',
    brand: 'Schneider',
    price: 132,
    description: '',
    image: '',
    series: 'Asfora',
    series_id: '1',
    brand_id: '1',
  },
  {
    id: 3,
    vendorCode: '3',
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    measurementUnit: 'шт',
    brand: 'Schneider',
    price: 223,
    description: '',
    image: '',
    series: 'Asfora',
    series_id: '1',
    brand_id: '1',
  },
  {
    id: 4,
    vendorCode: '4',
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    measurementUnit: 'шт',
    brand: 'Schneider',
    price: 323,
    description: '',
    image: '',
    series: 'Asfora',
    series_id: '1',
    brand_id: '1',
  },
  {
    id: 5,
    vendorCode: '5',
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    measurementUnit: 'шт',
    brand: 'Schneider',
    price: 523,
    description: '',
    image: '',
    series: 'Asfora',
    series_id: '1',
    brand_id: '1',
  },
];
