export const products = [
  {
    id: 1,
    images: null,
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    article: '',
    unit_of_measurement: 'шт',
    price: 4443,
    description: '',
    in_stock: false,
    popular: true,
    brand_id: 1,
    series_id: 1,
    subseries_id: 1,
    updated_info_date: '',
    add_date: '',
  },
  {
    id: 2,
    images: null,
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    article: '',
    unit_of_measurement: 'шт',
    price: 4443,
    description: '',
    in_stock: false,
    popular: true,
    brand_id: 1,
    series_id: 1,
    subseries_id: 1,
    updated_info_date: '',
    add_date: '',
  },
  {
    id: 3,
    images: null,
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    article: '',
    unit_of_measurement: 'шт',
    price: 4443,
    description: '',
    in_stock: false,
    popular: true,
    brand_id: 1,
    series_id: 1,
    subseries_id: 1,
    updated_info_date: '',
    add_date: '',
  },
  {
    id: 4,
    images: null,
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    article: '',
    unit_of_measurement: 'шт',
    price: 4443,
    description: '',
    in_stock: false,
    popular: true,
    brand_id: 1,
    series_id: 1,
    subseries_id: 1,
    updated_info_date: '',
    add_date: '',
  },
  {
    id: 5,
    images: null,
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    article: '',
    unit_of_measurement: 'шт',
    price: 4443,
    description: '',
    in_stock: false,
    popular: true,
    brand_id: 1,
    series_id: 1,
    subseries_id: 1,
    updated_info_date: '',
    add_date: '',
  },
  {
    id: 6,
    images: null,
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    article: '',
    unit_of_measurement: 'шт',
    price: 4443,
    description: '',
    in_stock: false,
    popular: true,
    brand_id: 1,
    series_id: 1,
    subseries_id: 1,
    updated_info_date: '',
    add_date: '',
  },
];
