export const products = [
  {
    id: 1,
    images: null,
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    article: 'EPH2970121',
    unit_of_measurement: 'шт',
    price: 756.08,
    description:
      'Розетка Schneider Electric Asfora EPH2970121, механізм із супортом та накладкою білого кольору. Конфігурація полюсів 2P + E, розетка оснащена боковим заземленням. Фіксація пристрою за допомогою гвинтів та монтажних лапок. Номінальний струм 16А, діапазон потужності 3680 Вт. Розміри вимикача: (Ш) 71 мм x (В) 71 мм x (Г) 42 мм, глибина встановлення 10 мм. Пристрій може бути встановленний приховано. Поверхня розетки глянцева, що надає приміщенню елегантного та вишуканого вигляду. Ступінь захисту IP20. Обладнана самозатискними клемами. Розетка виготовлена з ABS (акрилонітрил-бутадієн-стирол) матеріалу, що робить її максимально стійкою. Мідний провідниковий матеріал забезпечує надійність. Має сертифікати TSE, VDE. Оновлена фурнітура Asfora тепер має менші, компактніші накладки, профільований супорт, а також широкі, профільовані монтажні лапки з поворотною пружиною, тим самим покращуючи якість та функціональність пристроїв. Продукція Asfora виготовлена з високоякісних матеріалів, які не жовтіють з часом. Витончений, елегантний дизайн ідеально гармонує з будь-яким інтер',
    in_stock: false,
    popular: true,
    brand_id: 26,
    series_id: 1,
    subseries_id: 1,
    updated_info_date: '',
    add_date: '',
  },
  {
    id: 2,
    images: null,
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    article: '',
    unit_of_measurement: 'шт',
    price: 4443,
    description: '',
    in_stock: false,
    popular: true,
    brand_id: 1,
    series_id: 1,
    subseries_id: 1,
    updated_info_date: '',
    add_date: '',
  },
  {
    id: 3,
    images: null,
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    article: '',
    unit_of_measurement: 'шт',
    price: 4443,
    description: '',
    in_stock: false,
    popular: true,
    brand_id: 1,
    series_id: 1,
    subseries_id: 1,
    updated_info_date: '',
    add_date: '',
  },
  {
    id: 4,
    images: null,
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    article: '',
    unit_of_measurement: 'шт',
    price: 4443,
    description: '',
    in_stock: false,
    popular: true,
    brand_id: 1,
    series_id: 1,
    subseries_id: 1,
    updated_info_date: '',
    add_date: '',
  },
  {
    id: 5,
    images: null,
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    article: '',
    unit_of_measurement: 'шт',
    price: 4443,
    description: '',
    in_stock: false,
    popular: true,
    brand_id: 1,
    series_id: 1,
    subseries_id: 1,
    updated_info_date: '',
    add_date: '',
  },
  {
    id: 6,
    images: null,
    name: 'Розетка з заземленням Schneider Electric Asfora Білий',
    article: '',
    unit_of_measurement: 'шт',
    price: 4443,
    description: '',
    in_stock: false,
    popular: true,
    brand_id: 1,
    series_id: 1,
    subseries_id: 1,
    updated_info_date: '',
    add_date: '',
  },
];
