export { default as HeartIcon } from './HeartIcon'
export { default as TikTokIcon } from './TikTokIcon'
export { default as InstagramIcon } from './InstagramIcon'
export { default as PhoneIcon } from './PhoneIcon'
export { default as CartIcon } from './CartIcon'
export { default as MainLogo } from './MainLogo'
export { default as SearchIcon } from './SearchIcon'
